In [8]:
import pandas as pd
org_data_path = "../CHESS/data/df_3.csv"
df_3 = pd.read_csv(org_data_path)
# Eliminar empate ya que no abona al objetivo
df_3 = df_3[df_3['winner'] != 'Draw']
df_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19108 entries, 0 to 20057
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   game_id             19108 non-null  int64
 1   rated               19108 non-null  bool
 2   turns               19108 non-null  int64
 3   winner              19108 non-null  object
 4   time_increment      19108 non-null  object
 5   white_rating        19108 non-null  int64
 6   black_rating        19108 non-null  int64
 7   moves               19108 non-null  object
 8   opening_code        19108 non-null  object
 9   opening_moves       19108 non-null  int64
 10  opening_fullname    19108 non-null  object
 11  opening_shortname   19108 non-null  object
 12  opening_variation   19108 non-null  object
 13  moves_fen           19108 non-null  object
 14  current_turn        19108 non-null  bool
 15  w_ctrld_pawn        19108 non-null  int64
 16  w_ctrld_knight      19108 non-null  int64
 17  w_ctrld_bishop      19108 non-null  int64
 18  w_ctrld_rook        19108 non-null  int64
 19  w_ctrld_queen       19108 non-null  int64
 20  w_ctrld_king        19108 non-null  int64
 21  w_preassure_points  19108 non-null  int64
 22  w_ctrld_diagonals   19108 non-null  int64
 23  w_ctrld_lines       19108 non-null  int64
 24  b_ctrld_pawn        19108 non-null  int64
 25  b_ctrld_knight      19108 non-null  int64
 26  b_ctrld_bishop      19108 non-null  int64
 27  b_ctrld_rook        19108 non-null  int64
 28  b_ctrld_queen       19108 non-null  int64
 29  b_ctrld_king        19108 non-null  int64
 30  b_preassure_points  19108 non-null  int64
 31  b_ctrld_diagonals   19108 non-null  int64
 32  b_ctrld_lines       19108 non-null  int64
dtypes: bool(2), int64(23), object(8)
memory usage: 4.7+ MB

In [9]:
from sklearn.preprocessing import LabelEncoder
# Codificando todas las variables categóricas consideradas en valores numéricos
le1 = LabelEncoder() #rated
le2 = LabelEncoder() #winner
le3 = LabelEncoder() #time_increment
le4 = LabelEncoder() #opening_code
le5 = LabelEncoder() #opening_fullname
le6 = LabelEncoder() #opening_shortname
le7 = LabelEncoder() #opening_variation
le8 = LabelEncoder() #moves_fen
le9 = LabelEncoder() #current_turn

# Apply label encoding to each categorical column
df_3['rated_cod'] = le1.fit_transform(df_3['rated']) # Ordinal
df_3['winner_cod'] = le2.fit_transform(df_3['winner']) # No ordinal, pero solo tres clases
df_3['current_turn_cod'] = le9.fit_transform(df_3['current_turn']) # Ordinal
df_3['time_increment_cod'] = le3.fit_transform(df_3['time_increment']) # Ordinal
df_3['opening_code_cod'] = le4.fit_transform(df_3['opening_code']) # No ordinal, muchas categorias
df_3['opening_fullname_cod'] = le5.fit_transform(df_3['opening_fullname']) # No ordinal, muchas categorias
df_3['opening_shortname_cod'] = le6.fit_transform(df_3['opening_shortname']) # No ordinal, muchas categorias
df_3['opening_variation_cod'] = le7.fit_transform(df_3['opening_variation']) # No ordinal, muchas categorias
df_3['moves_fen_cod'] = le8.fit_transform(df_3['moves_fen']) # No ordinal, muchas categorias

In [10]:
pares_unicos = df_3[['winner', 'winner_cod']].drop_duplicates()
pares_unicos

  winner  winner_cod
0  White           1
1  Black           0

In [11]:
pares_unicos = df_3[['opening_fullname_cod', 'opening_fullname']].drop_duplicates()
pares_unicos

       opening_fullname_cod                                   opening_fullname
0                      1363                   Slav Defense: Exchange Variation
1                       739             Nimzowitsch Defense: Kennedy Variation
2                       642              King's Pawn Game: Leonardis Variation
3                       976             Queen's Pawn Game: Zukertort Variation
4                       771                                   Philidor Defense
...                     ...                                                ...
19938                  1320  Sicilian Defense: Scheveningen Variation |  En...
19979                   801  Pirc Defense: Austrian Attack |  Kurajica Vari...
19982                   934  Queen's Indian Defense: Classical Variation | ...
20000                   899   Queen's Gambit Declined: Slav |  Dutch Variation
20018                  1281  Sicilian Defense: Najdorf Variation |  Polugae...

[1453 rows x 2 columns]

In [12]:
df_3.to_csv("../CHESS/data/df_3_cod.csv", index=False) # Data frame con features basadas en ventaja posicional del turno